//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.52  Mar. 28, 2005 
// Sat May 24 11:45:53 2014
//
//      Input file         : M:/2012EDA/signal2/signal2_lab/lab4imagenoise/DE2_115_SOBEL_SDC/mdianfilter/averagefilter.vhd
//      Design name        : averagefilter
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//
//定义实体
module averagefilter (clk, m11, m12, m13, m21, m22, m23, m31, m32, m33, mid);

   parameter width  = 8;
   input clk; 
   input[width - 1:0] m11; 
   input[width - 1:0] m12; 
   input[width - 1:0] m13; 
   input[width - 1:0] m21; 
   input[width - 1:0] m22; 
   input[width - 1:0] m23; 
   input[width - 1:0] m31; 
   input[width - 1:0] m32; 
   input[width - 1:0] m33; 
   output[width - 1:0] mid; 
   wire[width - 1:0] mid;

   wire[width + 2:0] tmp; 
   wire[width - 1:0] max1; 
   wire[width - 1:0] mid1; 
   wire[width - 1:0] min1; 
   wire[width - 1:0] max2; 
   wire[width - 1:0] mid2; 
   wire[width - 1:0] min2; 
   wire[width - 1:0] max3; 
   wire[width - 1:0] mid3; 
   wire[width - 1:0] min3; 
   wire[width - 1:0] max_min; 
   wire[width - 1:0] mid_mid; 
   wire[width - 1:0] min_max; 

   assign tmp = {3'b000, m11} + {3'b000, m12} + {3'b000, m13} + {3'b000, m21} + {3'b000, m22} + {3'b000, m23} + {3'b000, m31} + {3'b000, m32}  ;
   assign mid = tmp[width + 2:3] ;
endmodule
