//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.52  Mar. 28, 2005 
// Mon May 26 10:24:11 2014
//
//      Input file         : L:/2012EDA/signal2/signal2_lab/lab4imagenoise/DE2_115_SOBEL_SDC/mdianfilter/medianfilter.vhd
//      Design name        : medfilter
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//
//定义实体
module medfilter (clk, m11, m12, m13, m21, m22, m23, m31, m32, m33, mid);

   parameter width  = 8;
   input clk; 
   input[width - 1:0] m11; 
   input[width - 1:0] m12; 
   input[width - 1:0] m13; 
   input[width - 1:0] m21; 
   input[width - 1:0] m22; 
   input[width - 1:0] m23; 
   input[width - 1:0] m31; 
   input[width - 1:0] m32; 
   input[width - 1:0] m33; 
   output[width - 1:0] mid; 
   wire[width - 1:0] mid;

   wire[width - 1:0] max1; 
   wire[width - 1:0] mid1; 
   wire[width - 1:0] min1; 
   wire[width - 1:0] max2; 
   wire[width - 1:0] mid2; 
   wire[width - 1:0] min2; 
   wire[width - 1:0] max3; 
   wire[width - 1:0] mid3; 
   wire[width - 1:0] min3; 
   wire[width - 1:0] max_min; 
   wire[width - 1:0] mid_mid; 
   wire[width - 1:0] min_max; 

   tri_compare ul (
      clk, 
      m11, 
      m12, 
      m13, 
      max1, 
      mid1, 
      min1
   ); 
   tri_compare u2 (
      clk, 
      m21, 
      m22, 
      m23, 
      max2, 
      mid2, 
      min2
   ); 
   tri_compare u3 (
      clk, 
      m31, 
      m32, 
      m33, 
      max3, 
      mid3, 
      min3
   ); 
   tri_compare u4 (
      clk, 
      max1, 
      max2, 
      max3, 
      .min(max_min)
   ); 
   tri_compare u5 (
      clk, 
      mid1, 
      mid2, 
      mid3, 
      .mid(mid_mid)
   ); 
   tri_compare u6 (
      clk, 
      min1, 
      min2, 
      min3, 
      .max(min_max)
   ); 
   tri_compare u7 (
      clk, 
      max_min, 
      mid_mid, 
      min_max, 
      mid
   ); 
endmodule
