//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.52  Mar. 28, 2005 
// Mon May 26 10:24:11 2014
//
//      Input file         : L:/2012EDA/signal2/signal2_lab/lab4imagenoise/DE2_115_SOBEL_SDC/mdianfilter/medianfilter.vhd
//      Design name        : tri_compare
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//
module tri_compare (clk, a, b, c, max, mid, min);

   parameter width  = 8;
   input clk; 
   input[width - 1:0] a; 
   input[width - 1:0] b; 
   input[width - 1:0] c; 
   output[width - 1:0] max; 
   reg[width - 1:0] max;
   output[width - 1:0] mid; 
   reg[width - 1:0] mid;
   output[width - 1:0] min; 
   reg[width - 1:0] min;

   always @(clk)
   begin
      if (clk == 1'b1)
      begin
         if (a >= b & a >= c & b >= c)
         begin
            max <= a ; 
            mid <= b ; 
            min <= c ; 
         end
         else if (a >= b & a >= c & c >= b)
         begin
            max <= a ; 
            mid <= c ; 
            min <= b ; 
         end
         else if (b >= a & b >= c & a >= c)
         begin
            max <= b ; 
            mid <= a ; 
            min <= c ; 
         end
         else if (b >= a & b >= c & c >= a)
         begin
            max <= b ; 
            mid <= c ; 
            min <= a ; 
         end
         else if (c >= a & c >= b & a >= b)
         begin
            max <= c ; 
            mid <= a ; 
            min <= b ; 
         end
         else if (c >= a & c >= b & b >= a)
         begin
            max <= c ; 
            mid <= b ; 
            min <= a ; 
         end 
      end 
   end 
endmodule
