//altera_mult_add ACCUM_DIRECTION="ADD" ACCUM_SLOAD_ACLR="NONE" ACCUM_SLOAD_LATENCY_ACLR="NONE" ACCUM_SLOAD_LATENCY_CLOCK="UNREGISTERED" ACCUM_SLOAD_REGISTER="UNREGISTERED" ACCUMULATOR="NO" ADDNSUB_MULTIPLIER_ACLR1="NONE" ADDNSUB_MULTIPLIER_ACLR3="NONE" ADDNSUB_MULTIPLIER_LATENCY_ACLR1="NONE" ADDNSUB_MULTIPLIER_LATENCY_ACLR3="NONE" ADDNSUB_MULTIPLIER_LATENCY_CLOCK1="UNREGISTERED" ADDNSUB_MULTIPLIER_LATENCY_CLOCK3="UNREGISTERED" ADDNSUB_MULTIPLIER_REGISTER1="UNREGISTERED" ADDNSUB_MULTIPLIER_REGISTER3="UNREGISTERED" CBX_DECLARE_ALL_CONNECTED_PORTS="OFF" CHAINOUT_ADDER="NO" COEF0_0=0 COEF0_1=0 COEF0_2=0 COEF0_3=0 COEF0_4=0 COEF0_5=0 COEF0_6=0 COEF0_7=0 COEF1_0=0 COEF1_1=0 COEF1_2=0 COEF1_3=0 COEF1_4=0 COEF1_5=0 COEF1_6=0 COEF1_7=0 COEF2_0=0 COEF2_1=0 COEF2_2=0 COEF2_3=0 COEF2_4=0 COEF2_5=0 COEF2_6=0 COEF2_7=0 COEF3_0=0 COEF3_1=0 COEF3_2=0 COEF3_3=0 COEF3_4=0 COEF3_5=0 COEF3_6=0 COEF3_7=0 COEFSEL0_ACLR="NONE" COEFSEL0_LATENCY_ACLR="NONE" COEFSEL0_LATENCY_CLOCK="UNREGISTERED" COEFSEL0_REGISTER="UNREGISTERED" COEFSEL1_ACLR="NONE" COEFSEL1_LATENCY_ACLR="NONE" COEFSEL1_LATENCY_CLOCK="UNREGISTERED" COEFSEL1_REGISTER="UNREGISTERED" COEFSEL2_ACLR="NONE" COEFSEL2_LATENCY_ACLR="NONE" COEFSEL2_LATENCY_CLOCK="UNREGISTERED" COEFSEL2_REGISTER="UNREGISTERED" COEFSEL3_ACLR="NONE" COEFSEL3_LATENCY_ACLR="NONE" COEFSEL3_LATENCY_CLOCK="UNREGISTERED" COEFSEL3_REGISTER="UNREGISTERED" DEVICE_FAMILY="Cyclone V" DOUBLE_ACCUM="NO" DSP_BLOCK_BALANCING="Auto" INPUT_A0_LATENCY_ACLR="ACLR0" INPUT_A0_LATENCY_CLOCK="CLOCK0" INPUT_A1_LATENCY_ACLR="ACLR0" INPUT_A1_LATENCY_CLOCK="CLOCK0" INPUT_A2_LATENCY_ACLR="ACLR0" INPUT_A2_LATENCY_CLOCK="CLOCK0" INPUT_A3_LATENCY_ACLR="NONE" INPUT_A3_LATENCY_CLOCK="UNREGISTERED" INPUT_ACLR_A0="ACLR0" INPUT_ACLR_A1="ACLR0" INPUT_ACLR_A2="ACLR0" INPUT_ACLR_A3="NONE" INPUT_ACLR_B0="ACLR0" INPUT_ACLR_B1="ACLR0" INPUT_ACLR_B2="ACLR0" INPUT_ACLR_B3="NONE" INPUT_ACLR_C0="NONE" INPUT_ACLR_C1="NONE" INPUT_ACLR_C2="NONE" INPUT_ACLR_C3="NONE" INPUT_B0_LATENCY_ACLR="ACLR0" INPUT_B0_LATENCY_CLOCK="CLOCK0" INPUT_B1_LATENCY_ACLR="ACLR0" INPUT_B1_LATENCY_CLOCK="CLOCK0" INPUT_B2_LATENCY_ACLR="ACLR0" INPUT_B2_LATENCY_CLOCK="CLOCK0" INPUT_B3_LATENCY_ACLR="NONE" INPUT_B3_LATENCY_CLOCK="UNREGISTERED" INPUT_C0_LATENCY_ACLR="NONE" INPUT_C0_LATENCY_CLOCK="UNREGISTERED" INPUT_C1_LATENCY_ACLR="NONE" INPUT_C1_LATENCY_CLOCK="UNREGISTERED" INPUT_C2_LATENCY_ACLR="NONE" INPUT_C2_LATENCY_CLOCK="UNREGISTERED" INPUT_C3_LATENCY_ACLR="NONE" INPUT_C3_LATENCY_CLOCK="UNREGISTERED" INPUT_REGISTER_A0="CLOCK0" INPUT_REGISTER_A1="CLOCK0" INPUT_REGISTER_A2="CLOCK0" INPUT_REGISTER_A3="UNREGISTERED" INPUT_REGISTER_B0="CLOCK0" INPUT_REGISTER_B1="CLOCK0" INPUT_REGISTER_B2="CLOCK0" INPUT_REGISTER_B3="UNREGISTERED" INPUT_REGISTER_C0="UNREGISTERED" INPUT_REGISTER_C1="UNREGISTERED" INPUT_REGISTER_C2="UNREGISTERED" INPUT_REGISTER_C3="UNREGISTERED" INPUT_SOURCE_A0="DATAA" INPUT_SOURCE_A1="DATAA" INPUT_SOURCE_A2="DATAA" INPUT_SOURCE_A3="DATAA" INPUT_SOURCE_B0="DATAB" INPUT_SOURCE_B1="DATAB" INPUT_SOURCE_B2="DATAB" INPUT_SOURCE_B3="DATAB" LATENCY=2 LOADCONST_VALUE=64 MULTIPLIER1_DIRECTION="ADD" MULTIPLIER3_DIRECTION="ADD" MULTIPLIER_ACLR0="NONE" MULTIPLIER_ACLR1="NONE" MULTIPLIER_ACLR2="NONE" MULTIPLIER_ACLR3="NONE" MULTIPLIER_REGISTER0="UNREGISTERED" MULTIPLIER_REGISTER1="UNREGISTERED" MULTIPLIER_REGISTER2="UNREGISTERED" MULTIPLIER_REGISTER3="UNREGISTERED" NUMBER_OF_MULTIPLIERS=3 OUTPUT_ACLR="ACLR0" OUTPUT_REGISTER="CLOCK0" port_addnsub1="PORT_UNUSED" port_addnsub3="PORT_UNUSED" port_signa="PORT_UNUSED" port_signb="PORT_UNUSED" PREADDER_DIRECTION_0="ADD" PREADDER_DIRECTION_1="ADD" PREADDER_DIRECTION_2="ADD" PREADDER_DIRECTION_3="ADD" PREADDER_MODE="SIMPLE" REPRESENTATION_A="UNSIGNED" REPRESENTATION_B="SIGNED" SCANOUTA_ACLR="NONE" SCANOUTA_REGISTER="UNREGISTERED" SELECTED_DEVICE_FAMILY="Cyclone V" SIGNED_ACLR_A="NONE" SIGNED_ACLR_B="NONE" SIGNED_LATENCY_ACLR_A="NONE" SIGNED_LATENCY_ACLR_B="NONE" SIGNED_LATENCY_CLOCK_A="UNREGISTERED" SIGNED_LATENCY_CLOCK_B="UNREGISTERED" SIGNED_REGISTER_A="UNREGISTERED" SIGNED_REGISTER_B="UNREGISTERED" SYSTOLIC_ACLR1="NONE" SYSTOLIC_ACLR3="NONE" SYSTOLIC_DELAY1="UNREGISTERED" SYSTOLIC_DELAY3="UNREGISTERED" USE_SLOAD_ACCUM_PORT="NO" WIDTH_A=8 WIDTH_B=17 WIDTH_C=16 WIDTH_CHAININ=1 WIDTH_COEF=18 WIDTH_RESULT=27 aclr0 clock0 dataa datab result
//VERSION_BEGIN 16.1 cbx_altera_mult_add 2017:01:18:18:20:37:SJ cbx_altera_mult_add_rtl 2017:01:18:18:20:37:SJ cbx_mgl 2017:01:18:18:27:06:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



// Copyright (C) 2017  Intel Corporation. All rights reserved.
//  Your use of Intel Corporation's design tools, logic functions 
//  and other software and tools, and its AMPP partner logic 
//  functions, and any output files from any of the foregoing 
//  (including device programming or simulation files), and any 
//  associated documentation or information are expressly subject 
//  to the terms and conditions of the Intel Program License 
//  Subscription Agreement, the Intel Quartus Prime License Agreement,
//  the Intel MegaCore Function License Agreement, or other 
//  applicable license agreement, including, without limitation, 
//  that your use is for the sole purpose of programming logic 
//  devices manufactured by Intel and sold by Intel or its 
//  authorized distributors.  Please refer to the applicable 
//  agreement for further details.



//synthesis_resources = altera_mult_add_rtl 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  altera_mult_add_vp8c
	( 
	aclr0,
	clock0,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr0;
	input   clock0;
	input   [23:0]  dataa;
	input   [50:0]  datab;
	output   [26:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr0;
	tri1   clock0;
	tri0   [23:0]  dataa;
	tri0   [50:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [26:0]   wire_altera_mult_add_rtl1_result;

	altera_mult_add_rtl   altera_mult_add_rtl1
	( 
	.aclr0(aclr0),
	.chainout_sat_overflow(),
	.clock0(clock0),
	.dataa(dataa),
	.datab(datab),
	.mult0_is_saturated(),
	.mult1_is_saturated(),
	.mult2_is_saturated(),
	.mult3_is_saturated(),
	.overflow(),
	.result(wire_altera_mult_add_rtl1_result),
	.scanouta(),
	.scanoutb(),
	.accum_sload(1'b0),
	.aclr1(1'b0),
	.aclr2(1'b0),
	.aclr3(1'b0),
	.addnsub1(1'b1),
	.addnsub1_round(1'b0),
	.addnsub3(1'b1),
	.addnsub3_round(1'b0),
	.chainin({1{1'b0}}),
	.chainout_round(1'b0),
	.chainout_saturate(1'b0),
	.clock1(1'b1),
	.clock2(1'b1),
	.clock3(1'b1),
	.coefsel0({3{1'b0}}),
	.coefsel1({3{1'b0}}),
	.coefsel2({3{1'b0}}),
	.coefsel3({3{1'b0}}),
	.datac({48{1'b0}}),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.mult01_round(1'b0),
	.mult01_saturation(1'b0),
	.mult23_round(1'b0),
	.mult23_saturation(1'b0),
	.negate(1'b0),
	.output_round(1'b0),
	.output_saturate(1'b0),
	.rotate(1'b0),
	.scanina({8{1'b0}}),
	.scaninb({17{1'b0}}),
	.sclr0(1'b0),
	.sclr1(1'b0),
	.sclr2(1'b0),
	.sclr3(1'b0),
	.shift_right(1'b0),
	.signa(1'b0),
	.signb(1'b0),
	.sload_accum(1'b0),
	.sourcea({3{1'b0}}),
	.sourceb({3{1'b0}}),
	.zero_chainout(1'b0),
	.zero_loopback(1'b0)
	);
	defparam
		altera_mult_add_rtl1.accum_direction = "ADD",
		altera_mult_add_rtl1.accum_sload_aclr = "NONE",
		altera_mult_add_rtl1.accum_sload_latency_aclr = "NONE",
		altera_mult_add_rtl1.accum_sload_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.accum_sload_latency_sclr = "NONE",
		altera_mult_add_rtl1.accum_sload_register = "UNREGISTERED",
		altera_mult_add_rtl1.accum_sload_sclr = "NONE",
		altera_mult_add_rtl1.accumulator = "NO",
		altera_mult_add_rtl1.adder1_rounding = "NO",
		altera_mult_add_rtl1.adder3_rounding = "NO",
		altera_mult_add_rtl1.addnsub1_round_aclr = "NONE",
		altera_mult_add_rtl1.addnsub1_round_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.addnsub1_round_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub1_round_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.addnsub1_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub1_round_sclr = "NONE",
		altera_mult_add_rtl1.addnsub3_round_aclr = "NONE",
		altera_mult_add_rtl1.addnsub3_round_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.addnsub3_round_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub3_round_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.addnsub3_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub3_round_sclr = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_aclr1 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_aclr3 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_latency_aclr1 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_latency_aclr3 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_latency_clock1 = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub_multiplier_latency_clock3 = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub_multiplier_latency_sclr1 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_latency_sclr3 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_register1 = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub_multiplier_register3 = "UNREGISTERED",
		altera_mult_add_rtl1.addnsub_multiplier_sclr1 = "NONE",
		altera_mult_add_rtl1.addnsub_multiplier_sclr3 = "NONE",
		altera_mult_add_rtl1.chainout_aclr = "NONE",
		altera_mult_add_rtl1.chainout_adder = "NO",
		altera_mult_add_rtl1.chainout_adder_direction = "ADD",
		altera_mult_add_rtl1.chainout_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_round_aclr = "NONE",
		altera_mult_add_rtl1.chainout_round_output_aclr = "NONE",
		altera_mult_add_rtl1.chainout_round_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_round_output_sclr = "NONE",
		altera_mult_add_rtl1.chainout_round_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.chainout_round_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_round_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.chainout_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_round_sclr = "NONE",
		altera_mult_add_rtl1.chainout_rounding = "NO",
		altera_mult_add_rtl1.chainout_saturate_aclr = "NONE",
		altera_mult_add_rtl1.chainout_saturate_output_aclr = "NONE",
		altera_mult_add_rtl1.chainout_saturate_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_saturate_output_sclr = "NONE",
		altera_mult_add_rtl1.chainout_saturate_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.chainout_saturate_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_saturate_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.chainout_saturate_register = "UNREGISTERED",
		altera_mult_add_rtl1.chainout_saturate_sclr = "NONE",
		altera_mult_add_rtl1.chainout_saturation = "NO",
		altera_mult_add_rtl1.chainout_sclr = "NONE",
		altera_mult_add_rtl1.coef0_0 = 0,
		altera_mult_add_rtl1.coef0_1 = 0,
		altera_mult_add_rtl1.coef0_2 = 0,
		altera_mult_add_rtl1.coef0_3 = 0,
		altera_mult_add_rtl1.coef0_4 = 0,
		altera_mult_add_rtl1.coef0_5 = 0,
		altera_mult_add_rtl1.coef0_6 = 0,
		altera_mult_add_rtl1.coef0_7 = 0,
		altera_mult_add_rtl1.coef1_0 = 0,
		altera_mult_add_rtl1.coef1_1 = 0,
		altera_mult_add_rtl1.coef1_2 = 0,
		altera_mult_add_rtl1.coef1_3 = 0,
		altera_mult_add_rtl1.coef1_4 = 0,
		altera_mult_add_rtl1.coef1_5 = 0,
		altera_mult_add_rtl1.coef1_6 = 0,
		altera_mult_add_rtl1.coef1_7 = 0,
		altera_mult_add_rtl1.coef2_0 = 0,
		altera_mult_add_rtl1.coef2_1 = 0,
		altera_mult_add_rtl1.coef2_2 = 0,
		altera_mult_add_rtl1.coef2_3 = 0,
		altera_mult_add_rtl1.coef2_4 = 0,
		altera_mult_add_rtl1.coef2_5 = 0,
		altera_mult_add_rtl1.coef2_6 = 0,
		altera_mult_add_rtl1.coef2_7 = 0,
		altera_mult_add_rtl1.coef3_0 = 0,
		altera_mult_add_rtl1.coef3_1 = 0,
		altera_mult_add_rtl1.coef3_2 = 0,
		altera_mult_add_rtl1.coef3_3 = 0,
		altera_mult_add_rtl1.coef3_4 = 0,
		altera_mult_add_rtl1.coef3_5 = 0,
		altera_mult_add_rtl1.coef3_6 = 0,
		altera_mult_add_rtl1.coef3_7 = 0,
		altera_mult_add_rtl1.coefsel0_aclr = "NONE",
		altera_mult_add_rtl1.coefsel0_latency_aclr = "NONE",
		altera_mult_add_rtl1.coefsel0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel0_latency_sclr = "NONE",
		altera_mult_add_rtl1.coefsel0_register = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel0_sclr = "NONE",
		altera_mult_add_rtl1.coefsel1_aclr = "NONE",
		altera_mult_add_rtl1.coefsel1_latency_aclr = "NONE",
		altera_mult_add_rtl1.coefsel1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel1_latency_sclr = "NONE",
		altera_mult_add_rtl1.coefsel1_register = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel1_sclr = "NONE",
		altera_mult_add_rtl1.coefsel2_aclr = "NONE",
		altera_mult_add_rtl1.coefsel2_latency_aclr = "NONE",
		altera_mult_add_rtl1.coefsel2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel2_latency_sclr = "NONE",
		altera_mult_add_rtl1.coefsel2_register = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel2_sclr = "NONE",
		altera_mult_add_rtl1.coefsel3_aclr = "NONE",
		altera_mult_add_rtl1.coefsel3_latency_aclr = "NONE",
		altera_mult_add_rtl1.coefsel3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel3_latency_sclr = "NONE",
		altera_mult_add_rtl1.coefsel3_register = "UNREGISTERED",
		altera_mult_add_rtl1.coefsel3_sclr = "NONE",
		altera_mult_add_rtl1.dedicated_multiplier_circuitry = "AUTO",
		altera_mult_add_rtl1.double_accum = "NO",
		altera_mult_add_rtl1.dsp_block_balancing = "Auto",
		altera_mult_add_rtl1.extra_latency = 0,
		altera_mult_add_rtl1.input_a0_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_a0_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_a0_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_a1_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_a1_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_a1_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_a2_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_a2_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_a2_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_a3_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_a3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_a3_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_aclr_a0 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_a1 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_a2 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_a3 = "NONE",
		altera_mult_add_rtl1.input_aclr_b0 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_b1 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_b2 = "ACLR0",
		altera_mult_add_rtl1.input_aclr_b3 = "NONE",
		altera_mult_add_rtl1.input_aclr_c0 = "NONE",
		altera_mult_add_rtl1.input_aclr_c1 = "NONE",
		altera_mult_add_rtl1.input_aclr_c2 = "NONE",
		altera_mult_add_rtl1.input_aclr_c3 = "NONE",
		altera_mult_add_rtl1.input_b0_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_b0_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_b0_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_b1_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_b1_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_b1_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_b2_latency_aclr = "ACLR0",
		altera_mult_add_rtl1.input_b2_latency_clock = "CLOCK0",
		altera_mult_add_rtl1.input_b2_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_b3_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_b3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_b3_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_c0_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_c0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_c0_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_c1_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_c1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_c1_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_c2_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_c2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_c2_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_c3_latency_aclr = "NONE",
		altera_mult_add_rtl1.input_c3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.input_c3_latency_sclr = "NONE",
		altera_mult_add_rtl1.input_register_a0 = "CLOCK0",
		altera_mult_add_rtl1.input_register_a1 = "CLOCK0",
		altera_mult_add_rtl1.input_register_a2 = "CLOCK0",
		altera_mult_add_rtl1.input_register_a3 = "UNREGISTERED",
		altera_mult_add_rtl1.input_register_b0 = "CLOCK0",
		altera_mult_add_rtl1.input_register_b1 = "CLOCK0",
		altera_mult_add_rtl1.input_register_b2 = "CLOCK0",
		altera_mult_add_rtl1.input_register_b3 = "UNREGISTERED",
		altera_mult_add_rtl1.input_register_c0 = "UNREGISTERED",
		altera_mult_add_rtl1.input_register_c1 = "UNREGISTERED",
		altera_mult_add_rtl1.input_register_c2 = "UNREGISTERED",
		altera_mult_add_rtl1.input_register_c3 = "UNREGISTERED",
		altera_mult_add_rtl1.input_sclr_a0 = "NONE",
		altera_mult_add_rtl1.input_sclr_a1 = "NONE",
		altera_mult_add_rtl1.input_sclr_a2 = "NONE",
		altera_mult_add_rtl1.input_sclr_a3 = "NONE",
		altera_mult_add_rtl1.input_sclr_b0 = "NONE",
		altera_mult_add_rtl1.input_sclr_b1 = "NONE",
		altera_mult_add_rtl1.input_sclr_b2 = "NONE",
		altera_mult_add_rtl1.input_sclr_b3 = "NONE",
		altera_mult_add_rtl1.input_sclr_c0 = "NONE",
		altera_mult_add_rtl1.input_sclr_c1 = "NONE",
		altera_mult_add_rtl1.input_sclr_c2 = "NONE",
		altera_mult_add_rtl1.input_sclr_c3 = "NONE",
		altera_mult_add_rtl1.input_source_a0 = "DATAA",
		altera_mult_add_rtl1.input_source_a1 = "DATAA",
		altera_mult_add_rtl1.input_source_a2 = "DATAA",
		altera_mult_add_rtl1.input_source_a3 = "DATAA",
		altera_mult_add_rtl1.input_source_b0 = "DATAB",
		altera_mult_add_rtl1.input_source_b1 = "DATAB",
		altera_mult_add_rtl1.input_source_b2 = "DATAB",
		altera_mult_add_rtl1.input_source_b3 = "DATAB",
		altera_mult_add_rtl1.latency = 2,
		altera_mult_add_rtl1.loadconst_control_aclr = "NONE",
		altera_mult_add_rtl1.loadconst_control_register = "UNREGISTERED",
		altera_mult_add_rtl1.loadconst_control_sclr = "NONE",
		altera_mult_add_rtl1.loadconst_value = 64,
		altera_mult_add_rtl1.mult01_round_aclr = "NONE",
		altera_mult_add_rtl1.mult01_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.mult01_round_sclr = "NONE",
		altera_mult_add_rtl1.mult01_saturation_aclr = "ACLR0",
		altera_mult_add_rtl1.mult01_saturation_register = "UNREGISTERED",
		altera_mult_add_rtl1.mult01_saturation_sclr = "ACLR0",
		altera_mult_add_rtl1.mult23_round_aclr = "NONE",
		altera_mult_add_rtl1.mult23_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.mult23_round_sclr = "NONE",
		altera_mult_add_rtl1.mult23_saturation_aclr = "NONE",
		altera_mult_add_rtl1.mult23_saturation_register = "UNREGISTERED",
		altera_mult_add_rtl1.mult23_saturation_sclr = "NONE",
		altera_mult_add_rtl1.multiplier01_rounding = "NO",
		altera_mult_add_rtl1.multiplier01_saturation = "NO",
		altera_mult_add_rtl1.multiplier1_direction = "ADD",
		altera_mult_add_rtl1.multiplier23_rounding = "NO",
		altera_mult_add_rtl1.multiplier23_saturation = "NO",
		altera_mult_add_rtl1.multiplier3_direction = "ADD",
		altera_mult_add_rtl1.multiplier_aclr0 = "NONE",
		altera_mult_add_rtl1.multiplier_aclr1 = "NONE",
		altera_mult_add_rtl1.multiplier_aclr2 = "NONE",
		altera_mult_add_rtl1.multiplier_aclr3 = "NONE",
		altera_mult_add_rtl1.multiplier_register0 = "UNREGISTERED",
		altera_mult_add_rtl1.multiplier_register1 = "UNREGISTERED",
		altera_mult_add_rtl1.multiplier_register2 = "UNREGISTERED",
		altera_mult_add_rtl1.multiplier_register3 = "UNREGISTERED",
		altera_mult_add_rtl1.multiplier_sclr0 = "NONE",
		altera_mult_add_rtl1.multiplier_sclr1 = "NONE",
		altera_mult_add_rtl1.multiplier_sclr2 = "NONE",
		altera_mult_add_rtl1.multiplier_sclr3 = "NONE",
		altera_mult_add_rtl1.negate_aclr = "NONE",
		altera_mult_add_rtl1.negate_latency_aclr = "NONE",
		altera_mult_add_rtl1.negate_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl1.negate_latency_sclr = "NONE",
		altera_mult_add_rtl1.negate_register = "UNREGISTERED",
		altera_mult_add_rtl1.negate_sclr = "NONE",
		altera_mult_add_rtl1.number_of_multipliers = 3,
		altera_mult_add_rtl1.output_aclr = "ACLR0",
		altera_mult_add_rtl1.output_register = "CLOCK0",
		altera_mult_add_rtl1.output_round_aclr = "NONE",
		altera_mult_add_rtl1.output_round_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.output_round_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.output_round_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.output_round_register = "UNREGISTERED",
		altera_mult_add_rtl1.output_round_sclr = "NONE",
		altera_mult_add_rtl1.output_round_type = "NEAREST_INTEGER",
		altera_mult_add_rtl1.output_rounding = "NO",
		altera_mult_add_rtl1.output_saturate_aclr = "NONE",
		altera_mult_add_rtl1.output_saturate_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.output_saturate_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.output_saturate_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.output_saturate_register = "UNREGISTERED",
		altera_mult_add_rtl1.output_saturate_sclr = "NONE",
		altera_mult_add_rtl1.output_saturate_type = "ASYMMETRIC",
		altera_mult_add_rtl1.output_saturation = "NO",
		altera_mult_add_rtl1.output_sclr = "NONE",
		altera_mult_add_rtl1.port_addnsub1 = "PORT_UNUSED",
		altera_mult_add_rtl1.port_addnsub3 = "PORT_UNUSED",
		altera_mult_add_rtl1.port_chainout_sat_is_overflow = "PORT_UNUSED",
		altera_mult_add_rtl1.port_negate = "PORT_UNUSED",
		altera_mult_add_rtl1.port_output_is_overflow = "PORT_UNUSED",
		altera_mult_add_rtl1.port_signa = "PORT_UNUSED",
		altera_mult_add_rtl1.port_signb = "PORT_UNUSED",
		altera_mult_add_rtl1.preadder_direction_0 = "ADD",
		altera_mult_add_rtl1.preadder_direction_1 = "ADD",
		altera_mult_add_rtl1.preadder_direction_2 = "ADD",
		altera_mult_add_rtl1.preadder_direction_3 = "ADD",
		altera_mult_add_rtl1.preadder_mode = "SIMPLE",
		altera_mult_add_rtl1.representation_a = "UNSIGNED",
		altera_mult_add_rtl1.representation_b = "SIGNED",
		altera_mult_add_rtl1.rotate_aclr = "NONE",
		altera_mult_add_rtl1.rotate_output_aclr = "NONE",
		altera_mult_add_rtl1.rotate_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.rotate_output_sclr = "NONE",
		altera_mult_add_rtl1.rotate_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.rotate_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.rotate_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.rotate_register = "UNREGISTERED",
		altera_mult_add_rtl1.rotate_sclr = "NONE",
		altera_mult_add_rtl1.scanouta_aclr = "NONE",
		altera_mult_add_rtl1.scanouta_register = "UNREGISTERED",
		altera_mult_add_rtl1.scanouta_sclr = "NONE",
		altera_mult_add_rtl1.selected_device_family = "Cyclone V",
		altera_mult_add_rtl1.shift_mode = "NO",
		altera_mult_add_rtl1.shift_right_aclr = "NONE",
		altera_mult_add_rtl1.shift_right_output_aclr = "NONE",
		altera_mult_add_rtl1.shift_right_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.shift_right_output_sclr = "NONE",
		altera_mult_add_rtl1.shift_right_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.shift_right_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.shift_right_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.shift_right_register = "UNREGISTERED",
		altera_mult_add_rtl1.shift_right_sclr = "NONE",
		altera_mult_add_rtl1.signed_aclr_a = "NONE",
		altera_mult_add_rtl1.signed_aclr_b = "NONE",
		altera_mult_add_rtl1.signed_latency_aclr_a = "NONE",
		altera_mult_add_rtl1.signed_latency_aclr_b = "NONE",
		altera_mult_add_rtl1.signed_latency_clock_a = "UNREGISTERED",
		altera_mult_add_rtl1.signed_latency_clock_b = "UNREGISTERED",
		altera_mult_add_rtl1.signed_latency_sclr_a = "NONE",
		altera_mult_add_rtl1.signed_latency_sclr_b = "NONE",
		altera_mult_add_rtl1.signed_register_a = "UNREGISTERED",
		altera_mult_add_rtl1.signed_register_b = "UNREGISTERED",
		altera_mult_add_rtl1.signed_sclr_a = "NONE",
		altera_mult_add_rtl1.signed_sclr_b = "NONE",
		altera_mult_add_rtl1.systolic_aclr1 = "NONE",
		altera_mult_add_rtl1.systolic_aclr3 = "NONE",
		altera_mult_add_rtl1.systolic_delay1 = "UNREGISTERED",
		altera_mult_add_rtl1.systolic_delay3 = "UNREGISTERED",
		altera_mult_add_rtl1.systolic_sclr1 = "NONE",
		altera_mult_add_rtl1.systolic_sclr3 = "NONE",
		altera_mult_add_rtl1.use_sload_accum_port = "NO",
		altera_mult_add_rtl1.use_subnadd = "NO",
		altera_mult_add_rtl1.width_a = 8,
		altera_mult_add_rtl1.width_b = 17,
		altera_mult_add_rtl1.width_c = 16,
		altera_mult_add_rtl1.width_chainin = 1,
		altera_mult_add_rtl1.width_coef = 18,
		altera_mult_add_rtl1.width_msb = 17,
		altera_mult_add_rtl1.width_result = 27,
		altera_mult_add_rtl1.width_saturate_sign = 1,
		altera_mult_add_rtl1.zero_chainout_output_aclr = "NONE",
		altera_mult_add_rtl1.zero_chainout_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.zero_chainout_output_sclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_aclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_output_aclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_output_register = "UNREGISTERED",
		altera_mult_add_rtl1.zero_loopback_output_sclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_pipeline_aclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_pipeline_register = "UNREGISTERED",
		altera_mult_add_rtl1.zero_loopback_pipeline_sclr = "NONE",
		altera_mult_add_rtl1.zero_loopback_register = "UNREGISTERED",
		altera_mult_add_rtl1.zero_loopback_sclr = "NONE",
		altera_mult_add_rtl1.lpm_type = "altera_mult_add_rtl";
	assign
		result = wire_altera_mult_add_rtl1_result;
endmodule //altera_mult_add_vp8c
//VALID FILE
