// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Jun 05 13:11:57 2018

digital_recognition digital_recognition_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.en(en_sig) ,	// input  en_sig
	.iEdge_Row(iEdge_Row_sig) ,	// input [17:0] iEdge_Row_sig
	.iEdge_Col(iEdge_Col_sig) ,	// input [17:0] iEdge_Col_sig
	.iRow(iRow_sig) ,	// input [8:0] iRow_sig
	.iCol(iCol_sig) ,	// input [8:0] iCol_sig
	.iBWData(iBWData_sig) ,	// input  iBWData_sig
	.oDigital(oDigital_sig) 	// output [3:0] oDigital_sig
);

