// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sun Jun 10 16:47:55 2018

edge_detection edge_detection_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.en(en_sig) ,	// input  en_sig
	.iRow(iRow_sig) ,	// input [9:0] iRow_sig
	.iCol(iCol_sig) ,	// input [9:0] iCol_sig
	.iHscan(iHscan_sig) ,	// input  iHscan_sig
	.iVscan(iVscan_sig) ,	// input  iVscan_sig
	.dataBW(dataBW_sig) ,	// input [9:0] dataBW_sig
	.oRow(oRow_sig) ,	// output [19:0] oRow_sig
	.oCol(oCol_sig) ,	// output [19:0] oCol_sig
	.ofinish(ofinish_sig) 	// output [1:0] ofinish_sig
);

