// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Jun 05 13:18:36 2018

img_process_xkw img_process_xkw_inst
(
	.oRed(oRed_sig) ,	// output [9:0] oRed_sig
	.oGreen(oGreen_sig) ,	// output [9:0] oGreen_sig
	.oBlue(oBlue_sig) ,	// output [9:0] oBlue_sig
	.oDigital(oDigital_sig) ,	// output [3:0] oDigital_sig
	.iVGA_X(iVGA_X_sig) ,	// input [10:0] iVGA_X_sig
	.iVGA_Y(iVGA_Y_sig) ,	// input [10:0] iVGA_Y_sig
	.iVGA_CLK(iVGA_CLK_sig) ,	// input  iVGA_CLK_sig
	.iRed(iRed_sig) ,	// input [9:0] iRed_sig
	.iGreen(iGreen_sig) ,	// input [9:0] iGreen_sig
	.iBlue(iBlue_sig) ,	// input [9:0] iBlue_sig
	.VGA_Read(VGA_Read_sig) ,	// input  VGA_Read_sig
	.SW(SW_sig) ,	// input [9:0] SW_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST(RST_sig) 	// input  RST_sig
);

