// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sun Jun 10 16:49:30 2018

rectangle rectangle_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.en(en_sig) ,	// input  en_sig
	.iRow(iRow_sig) ,	// input [19:0] iRow_sig
	.iCol(iCol_sig) ,	// input [19:0] iCol_sig
	.Row(Row_sig) ,	// input [9:0] Row_sig
	.Col(Col_sig) ,	// input [9:0] Col_sig
	.GRAY2BW(GRAY2BW_sig) ,	// input [9:0] GRAY2BW_sig
	.oBWrgb(oBWrgb_sig) 	// output [9:0] oBWrgb_sig
);

